// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: T:/Archivos UNLu/8vo cuatrimestre - 2025/Teoría de la Computación I - 2025/SegundaEntrega/Lexico.flex

package lexicoparte1;

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import lexicoparte1.TablaSimbolos;


@SuppressWarnings("fallthrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\2\1\22\0\1\1\1\3"+
    "\1\4\1\5\2\0\1\6\1\0\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\11\20\1\21"+
    "\1\22\1\23\1\24\1\25\2\0\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\2\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\37\1\45\1\46\1\47"+
    "\1\37\1\50\1\51\3\37\1\52\1\0\1\53\1\0"+
    "\1\54\1\0\6\55\1\54\1\56\22\54\1\0\1\57"+
    "\u0183\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\4\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\1\1\11\2\12\1\13\1\14\1\15"+
    "\1\16\1\17\12\20\1\21\1\22\1\1\1\23\1\0"+
    "\1\24\1\0\1\25\1\26\1\27\1\0\1\30\1\31"+
    "\1\32\3\20\1\33\1\34\1\20\1\35\5\20\1\36"+
    "\1\0\1\37\2\20\1\40\1\20\1\41\6\20\1\0"+
    "\1\20\1\42\3\20\1\43\2\20\1\44\1\20\1\0"+
    "\6\20\1\45\1\0\1\46\1\20\1\47\1\20\1\50"+
    "\1\51\1\0\1\20\1\52\1\0\1\20\1\0\1\53"+
    "\26\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\360\0\u0120\0\60"+
    "\0\60\0\60\0\60\0\60\0\60\0\u0150\0\60\0\u0180"+
    "\0\u01b0\0\60\0\60\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0"+
    "\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0\0\u0420"+
    "\0\60\0\60\0\u0450\0\60\0\u0480\0\60\0\360\0\60"+
    "\0\60\0\u0150\0\u04b0\0\60\0\60\0\60\0\u04e0\0\u0510"+
    "\0\u0540\0\u0270\0\u0270\0\u0570\0\u0270\0\u05a0\0\u05d0\0\u0600"+
    "\0\u0630\0\u0660\0\60\0\u0690\0\u04b0\0\u06c0\0\u06f0\0\u0720"+
    "\0\u0750\0\u0270\0\u0780\0\u07b0\0\u07e0\0\u0810\0\u0840\0\u0870"+
    "\0\u08a0\0\u08d0\0\u0270\0\u0900\0\u0930\0\u0960\0\u0270\0\u0990"+
    "\0\u09c0\0\u0270\0\u09f0\0\u0a20\0\u0a50\0\u0a80\0\u0ab0\0\u0ae0"+
    "\0\u0b10\0\u0b40\0\u0270\0\u0b70\0\u0270\0\u0ba0\0\u0270\0\u0bd0"+
    "\0\u0270\0\u0270\0\u0c00\0\u0c30\0\u0270\0\u0c60\0\u0c90\0\u0cc0"+
    "\0\u0270\0\u0cf0\0\u0d20\0\u0d50\0\u0d80\0\u0db0\0\u0de0\0\u0e10"+
    "\0\u0e40\0\u0e70\0\u0ea0\0\u0ed0\0\u0f00\0\u0f30\0\u0f60\0\u0f90"+
    "\0\u0fc0\0\u0ff0\0\u1020\0\u1050\0\u1080\0\u10b0\0\u10e0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\3\27\1\30\1\31"+
    "\1\32\2\27\1\33\2\27\1\34\3\27\1\35\1\36"+
    "\1\37\1\27\1\40\1\41\1\42\3\2\1\43\61\0"+
    "\2\3\101\0\1\44\33\0\2\45\1\0\1\45\1\46"+
    "\53\45\5\47\1\50\52\47\6\0\1\51\70\0\2\52"+
    "\54\0\1\52\1\0\2\21\14\0\1\53\20\0\1\53"+
    "\16\0\1\52\1\0\2\21\63\0\1\54\57\0\1\55"+
    "\57\0\1\56\52\0\2\27\5\0\24\27\2\0\3\27"+
    "\20\0\2\27\5\0\4\27\1\57\17\27\2\0\3\27"+
    "\20\0\2\27\5\0\12\27\1\60\1\27\1\61\7\27"+
    "\2\0\3\27\20\0\2\27\5\0\16\27\1\62\5\27"+
    "\2\0\3\27\20\0\2\27\5\0\5\27\1\63\6\27"+
    "\1\64\1\27\1\65\5\27\2\0\3\27\20\0\2\27"+
    "\5\0\15\27\1\66\6\27\2\0\3\27\20\0\2\27"+
    "\5\0\4\27\1\67\17\27\2\0\3\27\20\0\2\27"+
    "\5\0\21\27\1\70\2\27\2\0\3\27\20\0\2\27"+
    "\5\0\7\27\1\71\14\27\2\0\3\27\20\0\2\27"+
    "\5\0\7\27\1\72\14\27\2\0\3\27\60\0\1\73"+
    "\2\74\1\0\1\74\1\46\53\74\17\0\2\75\5\0"+
    "\6\75\21\0\1\75\21\0\2\27\5\0\2\27\1\76"+
    "\21\27\2\0\3\27\20\0\2\27\5\0\20\27\1\77"+
    "\3\27\2\0\3\27\20\0\2\27\5\0\3\27\1\100"+
    "\20\27\2\0\3\27\20\0\2\27\5\0\12\27\1\101"+
    "\6\27\1\102\2\27\2\0\3\27\20\0\2\27\5\0"+
    "\20\27\1\103\3\27\2\0\3\27\20\0\2\27\5\0"+
    "\1\104\15\27\1\105\5\27\2\0\3\27\20\0\2\27"+
    "\5\0\17\27\1\106\4\27\2\0\3\27\20\0\2\27"+
    "\5\0\4\27\1\107\17\27\2\0\3\27\20\0\2\27"+
    "\5\0\10\27\1\110\13\27\2\0\3\27\1\0\2\111"+
    "\1\0\1\111\1\46\53\111\17\0\2\27\5\0\22\27"+
    "\1\112\1\27\2\0\3\27\20\0\2\27\5\0\4\27"+
    "\1\113\17\27\2\0\3\27\20\0\2\27\5\0\3\27"+
    "\1\114\20\27\2\0\3\27\20\0\2\27\5\0\10\27"+
    "\1\115\13\27\2\0\3\27\20\0\2\27\5\0\21\27"+
    "\1\116\2\27\2\0\3\27\20\0\2\27\5\0\12\27"+
    "\1\117\11\27\2\0\3\27\20\0\2\27\5\0\4\27"+
    "\1\120\17\27\2\0\3\27\20\0\2\27\5\0\10\27"+
    "\1\121\13\27\2\0\3\27\20\0\2\27\5\0\14\27"+
    "\1\122\7\27\2\0\3\27\20\0\2\27\5\0\12\27"+
    "\1\123\11\27\2\0\3\27\1\0\2\124\1\0\1\124"+
    "\1\46\53\124\17\0\2\27\5\0\1\125\23\27\2\0"+
    "\3\27\20\0\2\27\5\0\4\27\1\126\17\27\2\0"+
    "\3\27\20\0\2\27\5\0\20\27\1\127\3\27\2\0"+
    "\3\27\20\0\2\27\5\0\17\27\1\130\4\27\2\0"+
    "\3\27\20\0\2\27\5\0\1\131\23\27\2\0\3\27"+
    "\20\0\2\27\5\0\14\27\1\132\7\27\2\0\3\27"+
    "\20\0\2\27\5\0\4\27\1\133\17\27\2\0\3\27"+
    "\1\0\2\134\1\0\1\134\1\46\53\134\17\0\2\27"+
    "\5\0\17\27\1\135\4\27\2\0\3\27\20\0\2\27"+
    "\5\0\2\27\1\136\21\27\2\0\3\27\20\0\2\27"+
    "\5\0\21\27\1\137\2\27\2\0\3\27\20\0\2\27"+
    "\5\0\1\140\23\27\2\0\3\27\20\0\2\27\5\0"+
    "\21\27\1\141\2\27\2\0\3\27\20\0\2\27\5\0"+
    "\6\27\1\142\15\27\2\0\3\27\1\0\2\143\1\0"+
    "\1\143\1\46\53\143\17\0\2\27\5\0\22\27\1\144"+
    "\1\27\2\0\3\27\20\0\2\27\5\0\17\27\1\145"+
    "\4\27\2\0\3\27\1\0\2\146\1\0\1\146\1\46"+
    "\53\146\17\0\2\27\5\0\1\147\23\27\2\0\3\27"+
    "\1\0\2\150\1\0\1\150\1\46\53\150\17\0\2\27"+
    "\5\0\17\27\1\151\4\27\2\0\3\27\1\0\2\152"+
    "\1\0\1\152\1\46\53\152\2\153\1\0\1\153\1\46"+
    "\53\153\2\154\1\0\1\154\1\46\53\154\2\155\1\0"+
    "\1\155\1\46\53\155\2\156\1\0\1\156\1\46\53\156"+
    "\2\157\1\0\1\157\1\46\53\157\2\160\1\0\1\160"+
    "\1\46\53\160\2\161\1\0\1\161\1\46\53\161\2\162"+
    "\1\0\1\162\1\46\53\162\2\163\1\0\1\163\1\46"+
    "\53\163\2\164\1\0\1\164\1\46\53\164\2\165\1\0"+
    "\1\165\1\46\53\165\2\166\1\0\1\166\1\46\53\166"+
    "\2\167\1\0\1\167\1\46\53\167\2\170\1\0\1\170"+
    "\1\46\53\170\2\171\1\0\1\171\1\46\53\171\2\172"+
    "\1\0\1\172\1\46\53\172\2\173\1\0\1\173\1\46"+
    "\53\173\2\174\1\0\1\174\1\46\53\174\2\175\1\0"+
    "\1\175\1\46\53\175\2\176\1\0\1\176\1\46\53\176"+
    "\2\177\1\0\1\177\1\46\53\177\4\0\1\46\53\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4368];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\6\11\1\1\1\11\2\1\2\11"+
    "\15\1\2\11\1\1\1\11\1\0\1\11\1\0\2\11"+
    "\1\1\1\0\3\11\14\1\1\11\1\0\14\1\1\0"+
    "\12\1\1\0\7\1\1\0\6\1\1\0\2\1\1\0"+
    "\1\1\1\0\1\1\26\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
   TablaSimbolos tablaSimbolos = new TablaSimbolos();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Caracter no permitido: <" + yytext() + "> en la línea " + yyline);
            }
          // fall through
          case 44: break;
          case 2:
            { /* Ignorar espacios */
            }
          // fall through
          case 45: break;
          case 3:
            { return new Symbol(sym.APARENT, yytext());
            }
          // fall through
          case 46: break;
          case 4:
            { return new Symbol(sym.CPARENT, yytext());
            }
          // fall through
          case 47: break;
          case 5:
            { return new Symbol(sym.MULT, yytext());
            }
          // fall through
          case 48: break;
          case 6:
            { return new Symbol(sym.SUMA, yytext());
            }
          // fall through
          case 49: break;
          case 7:
            { return new Symbol(sym.COMA, yytext());
            }
          // fall through
          case 50: break;
          case 8:
            { return new Symbol(sym.MENOS, yytext());
            }
          // fall through
          case 51: break;
          case 9:
            { return new Symbol(sym.DIV, yytext());
            }
          // fall through
          case 52: break;
          case 10:
            { int valor = Integer.parseInt(yytext());
       if (valor < 0 || valor > 32767) {
          throw new Error("Error: constante entera fuera de rango (0-32767): " + yytext() + " en la línea " + yyline);
       }
       tablaSimbolos.agregar(yytext(), "C_INT", valor, 0);
       return new Symbol(sym.C_INT, yytext());
            }
          // fall through
          case 53: break;
          case 11:
            { return new Symbol(sym.DOSPUNTOS, yytext());
            }
          // fall through
          case 54: break;
          case 12:
            { return new Symbol(sym.PYC, yytext());
            }
          // fall through
          case 55: break;
          case 13:
            { return new Symbol(sym.MENOR, yytext());
            }
          // fall through
          case 56: break;
          case 14:
            { return new Symbol(sym.ASIGNAR, yytext());
            }
          // fall through
          case 57: break;
          case 15:
            { return new Symbol(sym.MAYOR, yytext());
            }
          // fall through
          case 58: break;
          case 16:
            { if (tablaSimbolos.buscar(yytext()) == null) {
            tablaSimbolos.agregar(yytext(), "ID", null, 0);
        }
        return new Symbol(sym.ID, yytext());
            }
          // fall through
          case 59: break;
          case 17:
            { return new Symbol(sym.ACORCHETE, yytext());
            }
          // fall through
          case 60: break;
          case 18:
            { return new Symbol(sym.CCORCHETE, yytext());
            }
          // fall through
          case 61: break;
          case 19:
            { return new Symbol(sym.DISTINTO, yytext());
            }
          // fall through
          case 62: break;
          case 20:
            { String contenido = yytext().substring(1, yytext().length() - 1); // quitar comillas
       if (contenido.length() > 30) {
          throw new Error("Error: cadena demasiado larga (máx 30 caracteres): " + yytext() + " en la línea " + yyline);
       }
       tablaSimbolos.agregar(contenido, "C_STRING", "_" + contenido, contenido.length());
       return new Symbol(sym.C_STRING, yytext());
            }
          // fall through
          case 63: break;
          case 21:
            { /* Ignorar comentarios */
            }
          // fall through
          case 64: break;
          case 22:
            { return new Symbol(sym.AND, yytext());
            }
          // fall through
          case 65: break;
          case 23:
            { try {
          float valor = Float.parseFloat(yytext());
       } catch (NumberFormatException e) {
           throw new Error("Error: constante real inválida: " + yytext() + " en la línea " + yyline);
       }
       float valor = Float.parseFloat(yytext());
       tablaSimbolos.agregar(yytext(), "C_REAL", valor, 0);
       return new Symbol(sym.C_REAL, yytext());
            }
          // fall through
          case 66: break;
          case 24:
            { return new Symbol(sym.MENORIGUAL, yytext());
            }
          // fall through
          case 67: break;
          case 25:
            { return new Symbol(sym.IGUAL, yytext());
            }
          // fall through
          case 68: break;
          case 26:
            { return new Symbol(sym.MAYORIGUAL, yytext());
            }
          // fall through
          case 69: break;
          case 27:
            { return new Symbol(sym.FP,yytext());
            }
          // fall through
          case 70: break;
          case 28:
            { return new Symbol(sym.IF,yytext());
            }
          // fall through
          case 71: break;
          case 29:
            { return new Symbol(sym.IP,yytext());
            }
          // fall through
          case 72: break;
          case 30:
            { return new Symbol(sym.OR, yytext());
            }
          // fall through
          case 73: break;
          case 31:
            { return new Symbol(sym.HEX, yytext());
            }
          // fall through
          case 74: break;
          case 32:
            { return new Symbol(sym.END,yytext());
            }
          // fall through
          case 75: break;
          case 33:
            { return new Symbol(sym.INT,yytext());
            }
          // fall through
          case 76: break;
          case 34:
            { return new Symbol(sym.ELSE,yytext());
            }
          // fall through
          case 77: break;
          case 35:
            { return new Symbol(sym.REAL,yytext());
            }
          // fall through
          case 78: break;
          case 36:
            { return new Symbol(sym.THEN,yytext());
            }
          // fall through
          case 79: break;
          case 37:
            { return new Symbol(sym.WHILE,yytext());
            }
          // fall through
          case 80: break;
          case 38:
            { return new Symbol(sym.DECVAR,yytext());
            }
          // fall through
          case 81: break;
          case 39:
            { return new Symbol(sym.INLIST,yytext());
            }
          // fall through
          case 82: break;
          case 40:
            { return new Symbol(sym.REPEAT,yytext());
            }
          // fall through
          case 83: break;
          case 41:
            { return new Symbol(sym.STRING,yytext());
            }
          // fall through
          case 84: break;
          case 42:
            { return new Symbol(sym.MOSTRAR,yytext());
            }
          // fall through
          case 85: break;
          case 43:
            { return new Symbol(sym.ENDDECVAR,yytext());
            }
          // fall through
          case 86: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
