
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexicoparte1;

import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\071\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\021\003\000\002\021\004\000\002\017\006" +
    "\000\002\017\006\000\002\017\006\000\002\017\006\000" +
    "\002\003\005\000\002\004\004\000\002\004\003\000\002" +
    "\005\005\000\002\006\003\000\002\006\003\000\002\006" +
    "\003\000\002\022\004\000\002\022\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\007\003\000" +
    "\002\010\005\000\002\012\010\000\002\012\012\000\002" +
    "\011\007\000\002\013\003\000\002\013\005\000\002\013" +
    "\005\000\002\023\005\000\002\023\003\000\002\016\005" +
    "\000\002\014\005\000\002\014\010\000\002\015\003\000" +
    "\002\015\003\000\002\015\003\000\002\015\003\000\002" +
    "\015\003\000\002\015\003\000\002\024\005\000\002\024" +
    "\005\000\002\024\003\000\002\025\005\000\002\025\005" +
    "\000\002\025\003\000\002\026\003\000\002\026\003\000" +
    "\002\026\003\000\002\026\003\000\002\026\003\000\002" +
    "\026\005\000\002\020\006\000\002\020\006\000\002\020" +
    "\006\000\002\020\006\000\002\020\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\155\000\006\010\007\011\005\001\002\000\004\002" +
    "\157\001\002\000\004\022\145\001\002\000\006\002\uffff" +
    "\010\007\001\002\000\004\034\133\001\002\000\012\004" +
    "\013\005\020\010\016\022\022\001\002\000\006\002\ufffe" +
    "\010\ufffe\001\002\000\014\002\000\004\013\005\020\010" +
    "\016\022\022\001\002\000\012\004\013\005\020\010\016" +
    "\022\022\001\002\000\022\002\uffec\004\uffec\005\uffec\007" +
    "\uffec\010\uffec\016\uffec\022\uffec\053\uffec\001\002\000\022" +
    "\002\ufff0\004\ufff0\005\ufff0\007\ufff0\010\ufff0\016\ufff0\022" +
    "\ufff0\053\ufff0\001\002\000\004\034\114\001\002\000\022" +
    "\002\uffee\004\uffee\005\uffee\007\uffee\010\uffee\016\uffee\022" +
    "\uffee\053\uffee\001\002\000\020\015\050\022\030\024\026" +
    "\025\035\026\034\027\033\034\032\001\002\000\022\002" +
    "\uffed\004\uffed\005\uffed\007\uffed\010\uffed\016\uffed\022\uffed" +
    "\053\uffed\001\002\000\004\023\024\001\002\000\022\002" +
    "\uffef\004\uffef\005\uffef\007\uffef\010\uffef\016\uffef\022\uffef" +
    "\053\uffef\001\002\000\016\022\030\024\026\025\035\026" +
    "\034\027\033\034\032\001\002\000\062\002\uffd7\004\uffd7" +
    "\005\uffd7\006\uffd7\007\uffd7\010\uffd7\016\uffd7\022\uffd7\030" +
    "\uffd7\031\uffd7\032\043\033\044\035\uffd7\036\uffd7\040\uffd7" +
    "\041\uffd7\042\uffd7\043\uffd7\045\uffd7\046\uffd7\047\uffd7\050" +
    "\uffd7\052\uffd7\053\uffd7\001\002\000\062\002\uffd2\004\uffd2" +
    "\005\uffd2\006\uffd2\007\uffd2\010\uffd2\016\uffd2\022\uffd2\030" +
    "\uffd2\031\uffd2\032\uffd2\033\uffd2\035\uffd2\036\uffd2\040\uffd2" +
    "\041\uffd2\042\uffd2\043\uffd2\045\uffd2\046\uffd2\047\uffd2\050" +
    "\uffd2\052\uffd2\053\uffd2\001\002\000\026\002\uffeb\004\uffeb" +
    "\005\uffeb\007\uffeb\010\uffeb\016\uffeb\022\uffeb\030\037\031" +
    "\041\053\uffeb\001\002\000\062\002\uffd3\004\uffd3\005\uffd3" +
    "\006\uffd3\007\uffd3\010\uffd3\016\uffd3\022\uffd3\030\uffd3\031" +
    "\uffd3\032\uffd3\033\uffd3\035\uffd3\036\uffd3\040\uffd3\041\uffd3" +
    "\042\uffd3\043\uffd3\045\uffd3\046\uffd3\047\uffd3\050\uffd3\052" +
    "\uffd3\053\uffd3\001\002\000\062\002\uffd4\004\uffd4\005\uffd4" +
    "\006\uffd4\007\uffd4\010\uffd4\016\uffd4\022\uffd4\030\uffd4\031" +
    "\uffd4\032\uffd4\033\uffd4\035\uffd4\036\uffd4\040\uffd4\041\uffd4" +
    "\042\uffd4\043\uffd4\045\uffd4\046\uffd4\047\uffd4\050\uffd4\052" +
    "\uffd4\053\uffd4\001\002\000\016\022\030\024\026\025\035" +
    "\026\034\027\033\034\032\001\002\000\062\002\uffcf\004" +
    "\uffcf\005\uffcf\006\uffcf\007\uffcf\010\uffcf\016\uffcf\022\uffcf" +
    "\030\uffcf\031\uffcf\032\uffcf\033\uffcf\035\uffcf\036\uffcf\040" +
    "\uffcf\041\uffcf\042\uffcf\043\uffcf\045\uffcf\046\uffcf\047\uffcf" +
    "\050\uffcf\052\uffcf\053\uffcf\001\002\000\062\002\uffd0\004" +
    "\uffd0\005\uffd0\006\uffd0\007\uffd0\010\uffd0\016\uffd0\022\uffd0" +
    "\030\uffd0\031\uffd0\032\uffd0\033\uffd0\035\uffd0\036\uffd0\040" +
    "\uffd0\041\uffd0\042\uffd0\043\uffd0\045\uffd0\046\uffd0\047\uffd0" +
    "\050\uffd0\052\uffd0\053\uffd0\001\002\000\062\002\uffd1\004" +
    "\uffd1\005\uffd1\006\uffd1\007\uffd1\010\uffd1\016\uffd1\022\uffd1" +
    "\030\uffd1\031\uffd1\032\uffd1\033\uffd1\035\uffd1\036\uffd1\040" +
    "\uffd1\041\uffd1\042\uffd1\043\uffd1\045\uffd1\046\uffd1\047\uffd1" +
    "\050\uffd1\052\uffd1\053\uffd1\001\002\000\010\030\037\031" +
    "\041\035\040\001\002\000\016\022\030\024\026\025\035" +
    "\026\034\027\033\034\032\001\002\000\062\002\uffce\004" +
    "\uffce\005\uffce\006\uffce\007\uffce\010\uffce\016\uffce\022\uffce" +
    "\030\uffce\031\uffce\032\uffce\033\uffce\035\uffce\036\uffce\040" +
    "\uffce\041\uffce\042\uffce\043\uffce\045\uffce\046\uffce\047\uffce" +
    "\050\uffce\052\uffce\053\uffce\001\002\000\016\022\030\024" +
    "\026\025\035\026\034\027\033\034\032\001\002\000\062" +
    "\002\uffd8\004\uffd8\005\uffd8\006\uffd8\007\uffd8\010\uffd8\016" +
    "\uffd8\022\uffd8\030\uffd8\031\uffd8\032\043\033\044\035\uffd8" +
    "\036\uffd8\040\uffd8\041\uffd8\042\uffd8\043\uffd8\045\uffd8\046" +
    "\uffd8\047\uffd8\050\uffd8\052\uffd8\053\uffd8\001\002\000\016" +
    "\022\030\024\026\025\035\026\034\027\033\034\032\001" +
    "\002\000\016\022\030\024\026\025\035\026\034\027\033" +
    "\034\032\001\002\000\062\002\uffd5\004\uffd5\005\uffd5\006" +
    "\uffd5\007\uffd5\010\uffd5\016\uffd5\022\uffd5\030\uffd5\031\uffd5" +
    "\032\uffd5\033\uffd5\035\uffd5\036\uffd5\040\uffd5\041\uffd5\042" +
    "\uffd5\043\uffd5\045\uffd5\046\uffd5\047\uffd5\050\uffd5\052\uffd5" +
    "\053\uffd5\001\002\000\062\002\uffd6\004\uffd6\005\uffd6\006" +
    "\uffd6\007\uffd6\010\uffd6\016\uffd6\022\uffd6\030\uffd6\031\uffd6" +
    "\032\uffd6\033\uffd6\035\uffd6\036\uffd6\040\uffd6\041\uffd6\042" +
    "\uffd6\043\uffd6\045\uffd6\046\uffd6\047\uffd6\050\uffd6\052\uffd6" +
    "\053\uffd6\001\002\000\062\002\uffd9\004\uffd9\005\uffd9\006" +
    "\uffd9\007\uffd9\010\uffd9\016\uffd9\022\uffd9\030\uffd9\031\uffd9" +
    "\032\043\033\044\035\uffd9\036\uffd9\040\uffd9\041\uffd9\042" +
    "\uffd9\043\uffd9\045\uffd9\046\uffd9\047\uffd9\050\uffd9\052\uffd9" +
    "\053\uffd9\001\002\000\004\034\101\001\002\000\012\006" +
    "\uffe7\016\uffe7\047\075\050\076\001\002\000\022\030\037" +
    "\031\041\040\066\041\065\042\071\043\067\045\072\046" +
    "\073\001\002\000\004\006\054\001\002\000\012\004\013" +
    "\005\020\010\016\022\022\001\002\000\016\004\013\005" +
    "\020\007\057\010\016\016\060\022\022\001\002\000\022" +
    "\002\ufff1\004\ufff1\005\ufff1\007\ufff1\010\ufff1\016\ufff1\022" +
    "\ufff1\053\ufff1\001\002\000\012\004\013\005\020\010\016" +
    "\022\022\001\002\000\004\005\061\001\002\000\022\002" +
    "\uffea\004\uffea\005\uffea\007\uffea\010\uffea\016\uffea\022\uffea" +
    "\053\uffea\001\002\000\014\004\013\005\020\010\016\016" +
    "\063\022\022\001\002\000\004\005\064\001\002\000\022" +
    "\002\uffe9\004\uffe9\005\uffe9\007\uffe9\010\uffe9\016\uffe9\022" +
    "\uffe9\053\uffe9\001\002\000\016\022\uffde\024\uffde\025\uffde" +
    "\026\uffde\027\uffde\034\uffde\001\002\000\016\022\uffdf\024" +
    "\uffdf\025\uffdf\026\uffdf\027\uffdf\034\uffdf\001\002\000\016" +
    "\022\uffdc\024\uffdc\025\uffdc\026\uffdc\027\uffdc\034\uffdc\001" +
    "\002\000\016\022\030\024\026\025\035\026\034\027\033" +
    "\034\032\001\002\000\016\022\uffdd\024\uffdd\025\uffdd\026" +
    "\uffdd\027\uffdd\034\uffdd\001\002\000\016\022\uffdb\024\uffdb" +
    "\025\uffdb\026\uffdb\027\uffdb\034\uffdb\001\002\000\016\022" +
    "\uffda\024\uffda\025\uffda\026\uffda\027\uffda\034\uffda\001\002" +
    "\000\016\006\uffe1\016\uffe1\030\037\031\041\047\uffe1\050" +
    "\uffe1\001\002\000\020\015\050\022\030\024\026\025\035" +
    "\026\034\027\033\034\032\001\002\000\020\015\050\022" +
    "\030\024\026\025\035\026\034\027\033\034\032\001\002" +
    "\000\006\006\uffe5\016\uffe5\001\002\000\006\006\uffe6\016" +
    "\uffe6\001\002\000\004\022\102\001\002\000\004\037\103" +
    "\001\002\000\004\051\105\001\002\000\004\035\113\001" +
    "\002\000\016\022\030\024\026\025\035\026\034\027\033" +
    "\034\032\001\002\000\012\030\037\031\041\036\uffe3\052" +
    "\uffe3\001\002\000\006\036\111\052\110\001\002\000\004" +
    "\035\uffe2\001\002\000\016\022\030\024\026\025\035\026" +
    "\034\027\033\034\032\001\002\000\012\030\037\031\041" +
    "\036\uffe4\052\uffe4\001\002\000\012\006\uffe0\016\uffe0\047" +
    "\uffe0\050\uffe0\001\002\000\014\022\115\024\121\025\116" +
    "\026\117\027\120\001\002\000\004\035\126\001\002\000" +
    "\004\035\125\001\002\000\004\035\124\001\002\000\004" +
    "\035\123\001\002\000\004\035\122\001\002\000\022\002" +
    "\uffcc\004\uffcc\005\uffcc\007\uffcc\010\uffcc\016\uffcc\022\uffcc" +
    "\053\uffcc\001\002\000\022\002\uffc9\004\uffc9\005\uffc9\007" +
    "\uffc9\010\uffc9\016\uffc9\022\uffc9\053\uffc9\001\002\000\022" +
    "\002\uffca\004\uffca\005\uffca\007\uffca\010\uffca\016\uffca\022" +
    "\uffca\053\uffca\001\002\000\022\002\uffcb\004\uffcb\005\uffcb" +
    "\007\uffcb\010\uffcb\016\uffcb\022\uffcb\053\uffcb\001\002\000" +
    "\022\002\uffcd\004\uffcd\005\uffcd\007\uffcd\010\uffcd\016\uffcd" +
    "\022\uffcd\053\uffcd\001\002\000\014\004\013\005\020\010" +
    "\016\022\022\053\130\001\002\000\020\015\050\022\030" +
    "\024\026\025\035\026\034\027\033\034\032\001\002\000" +
    "\004\016\132\001\002\000\022\002\uffe8\004\uffe8\005\uffe8" +
    "\007\uffe8\010\uffe8\016\uffe8\022\uffe8\053\uffe8\001\002\000" +
    "\012\024\137\025\134\026\135\027\136\001\002\000\004" +
    "\035\143\001\002\000\004\035\142\001\002\000\004\035" +
    "\141\001\002\000\004\035\140\001\002\000\006\002\ufffc" +
    "\010\ufffc\001\002\000\006\002\ufff9\010\ufff9\001\002\000" +
    "\006\002\ufffa\010\ufffa\001\002\000\006\002\ufffb\010\ufffb" +
    "\001\002\000\006\002\ufffd\010\ufffd\001\002\000\004\044" +
    "\152\001\002\000\006\012\ufff6\022\ufff6\001\002\000\006" +
    "\012\151\022\145\001\002\000\006\012\ufff7\022\ufff7\001" +
    "\002\000\012\004\ufff8\005\ufff8\010\ufff8\022\ufff8\001\002" +
    "\000\010\017\156\020\154\021\153\001\002\000\006\012" +
    "\ufff2\022\ufff2\001\002\000\006\012\ufff3\022\ufff3\001\002" +
    "\000\006\012\ufff5\022\ufff5\001\002\000\006\012\ufff4\022" +
    "\ufff4\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\155\000\012\002\003\003\007\017\010\021\005\001" +
    "\001\000\002\001\001\000\006\004\146\005\145\001\001" +
    "\000\004\017\143\001\001\000\002\001\001\000\016\007" +
    "\014\010\016\011\020\012\013\020\022\022\011\001\001" +
    "\000\002\001\001\000\014\007\055\010\016\011\020\012" +
    "\013\020\022\001\001\000\016\007\014\010\016\011\020" +
    "\012\013\020\022\022\126\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\013\052\014\050\024\051\025\024\026\030\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\024\026\025\024\026\030\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\024\035\025\024\026\030\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\025\046\026\030\001\001\000\002\001" +
    "\001\000\006\025\041\026\030\001\001\000\002\001\001" +
    "\000\004\026\045\001\001\000\004\026\044\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\015\067\001\001\000" +
    "\002\001\001\000\016\007\014\010\016\011\020\012\013" +
    "\020\022\022\054\001\001\000\014\007\055\010\016\011" +
    "\020\012\013\020\022\001\001\000\002\001\001\000\016" +
    "\007\014\010\016\011\020\012\013\020\022\022\061\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\007\055" +
    "\010\016\011\020\012\013\020\022\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\024\073\025\024\026\030\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\014\077\024\051\025\024\026" +
    "\030\001\001\000\012\014\076\024\051\025\024\026\030" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\016\103\001\001\000\002" +
    "\001\001\000\012\023\106\024\105\025\024\026\030\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\024\111\025\024\026\030\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\007" +
    "\055\010\016\011\020\012\013\020\022\001\001\000\014" +
    "\013\130\014\050\024\051\025\024\026\030\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\147\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\006\154\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public static TablaSimbolos TS = new TablaSimbolos();

    /** Metodo llamado automáticamente ante un error sintáctico. */
    public void syntax_error(Symbol s){
        System.out.println("Error en la linea " + (s.right+1) + " columna " + s.left + ". "
            + s + " no reconocido. valor " + s.value );
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {



  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= pgm EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // pgm ::= declaracion programa 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("pgm Regla 0 Compila correctamente llegando al simbolo start");
        RESULT = p;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pgm",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // pgm ::= lista_mostrar 
            {
              Object RESULT =null;
		 
        System.out.println("pgm Regla 0 Compila correctamente llegando al simbolo start");
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pgm",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_mostrar ::= mostrar_sin_id 
            {
              Object RESULT =null;
		 
        System.out.println("[Regla 42] Mostrar");
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_mostrar",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_mostrar ::= lista_mostrar mostrar_sin_id 
            {
              Object RESULT =null;
		 
        System.out.println("[Regla 43] Lista mostrar");
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_mostrar",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // mostrar_sin_id ::= MOSTRAR APARENT C_INT CPARENT 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int entright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 44] Mostrar C_INT = " + ent);
        RESULT = String.valueOf(ent);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mostrar_sin_id",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // mostrar_sin_id ::= MOSTRAR APARENT C_REAL CPARENT 
            {
              Object RESULT =null;
		int realleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int realright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object real = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 45] Mostrar C_REAL = " + real);
        RESULT = String.valueOf(real);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mostrar_sin_id",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // mostrar_sin_id ::= MOSTRAR APARENT C_STRING CPARENT 
            {
              Object RESULT =null;
		int strleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int strright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object str = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 46] Mostrar C_STRING = " + str);
        RESULT = String.valueOf(str);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mostrar_sin_id",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // mostrar_sin_id ::= MOSTRAR APARENT HEX CPARENT 
            {
              Object RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object h = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 47] Mostrar HEX = " + h);
        RESULT = String.valueOf(h);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mostrar_sin_id",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // declaracion ::= DECVAR lista_decl ENDDECVAR 
            {
              Object RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object ld = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 1] Declaracion de variables"); 
        RESULT = ld;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista_decl ::= lista_decl decl 
            {
              Object RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object ld = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 2] Lista de declaraciones");
        RESULT = ld;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_decl",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // lista_decl ::= decl 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 3] Declaracion");
        RESULT = d;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_decl",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // decl ::= ID DOSPUNTOS tipo 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 4] Declaracion de variable: " + id + " : " + t);
        
        TS.agregar(id.toString(), "ID", t.toString(), null, 0);
        
        RESULT = id;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // tipo ::= INT 
            {
              Object RESULT =null;
		 
        System.out.println("[Regla 5] Tipo entero");
        RESULT = "INT";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // tipo ::= REAL 
            {
              Object RESULT =null;
		 
        System.out.println("[Regla 6] Tipo real");
        RESULT = "REAL";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // tipo ::= STRING 
            {
              Object RESULT =null;
		 
        System.out.println("[Regla 7] Tipo string");
        RESULT = "STRING";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // programa ::= programa sentencia 
            {
              Object RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 8] Programa con sentencia");
        RESULT = p;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // programa ::= sentencia 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 9] Programa con sentencia unica");
        RESULT = s;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sentencia ::= mostrar 
            {
              Object RESULT =null;
		 
        System.out.println("[Regla 52] Mostrar");
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // sentencia ::= asignacion 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 10] Sentencia de asignacion");
        RESULT = a;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sentencia ::= iteracion 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 11] Sentencia de iteracion");
        RESULT = i;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sentencia ::= seleccion 
            {
              Object RESULT =null;
		int selleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int selright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object sel = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 12] Sentencia de seleccion");
        RESULT = sel;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // asignacion ::= ID ASIGNAR expresion 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 13] Asignacion: " + id + " = " + e);
        
        Simbolo s = TS.buscar(id.toString());
        
        RESULT = String.valueOf(e);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("asignacion",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // seleccion ::= IF condicion THEN programa END IF 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 
        System.out.println("[Regla 14] if sin else");
        RESULT = p;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("seleccion",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // seleccion ::= IF condicion THEN programa ELSE programa END IF 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int p1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int p1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object p1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int p2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int p2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object p2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 
        System.out.println("[Regla 15] if con else");
        RESULT = p1;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("seleccion",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // iteracion ::= REPEAT programa WHILE condicion END 
            {
              Object RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 16] Sentencia repeat");
        RESULT = p;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("iteracion",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // condicion ::= comparacion 
            {
              Object RESULT =null;
		int compleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int compright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object comp = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 17] Condicion comparacion");
        RESULT = comp;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // condicion ::= comparacion AND comparacion 
            {
              Object RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object c1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object c2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 18] Condicion AND");
        RESULT = String.valueOf(c1) + " AND " + String.valueOf(c2);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // condicion ::= comparacion OR comparacion 
            {
              Object RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object c1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object c2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 19] Condicion OR");
        RESULT = String.valueOf(c1) + " OR " + String.valueOf(c2);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // lista_expresiones ::= lista_expresiones PYC expresion 
            {
              Object RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int leright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object le = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 20] Lista de expresiones");
        RESULT = le;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_expresiones",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // lista_expresiones ::= expresion 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 21] Expresion");
        RESULT = e;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_expresiones",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // lista_valores ::= ACORCHETE lista_expresiones CCORCHETE 
            {
              Object RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int leright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object le = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 22] Lista de valores");
        RESULT = le;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_valores",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // comparacion ::= expresion comparador expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int compleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int compright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object comp = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 23] Comparacion: " + e1 + " " + comp + " " + e2);
        RESULT = String.valueOf(e1) + String.valueOf(comp) + String.valueOf(e2);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comparacion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // comparacion ::= INLIST APARENT ID COMA lista_valores CPARENT 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int lvleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lvright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object lv = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 24] Funcion Inlist(" + id + ", " + lv + ")");
        RESULT = "INLIST(" + id + ")";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comparacion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // comparador ::= MENOR 
            {
              Object RESULT =null;
		 
        System.out.println("[Regla 25] Comparador <");
        RESULT = "<";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comparador",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // comparador ::= MENORIGUAL 
            {
              Object RESULT =null;
		 
        System.out.println("[Regla 26] Comparador <=");
        RESULT = "<=";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comparador",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // comparador ::= MAYOR 
            {
              Object RESULT =null;
		 
        System.out.println("[Regla 27] Comparador >");
        RESULT = ">";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comparador",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // comparador ::= MAYORIGUAL 
            {
              Object RESULT =null;
		 
        System.out.println("[Regla 28] Comparador >=");
        RESULT = ">=";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comparador",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // comparador ::= IGUAL 
            {
              Object RESULT =null;
		 
        System.out.println("[Regla 29] Comparador ==");
        RESULT = "==";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comparador",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // comparador ::= DISTINTO 
            {
              Object RESULT =null;
		 
        System.out.println("[Regla 30] Comparador !=");
        RESULT = "!=";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comparador",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expresion ::= expresion SUMA termino 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 31] E + T = " + e + " + " + t);
        RESULT = String.valueOf(e) + "+" + String.valueOf(t);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expresion ::= expresion MENOS termino 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 32] E - T = " + e + " - " + t);
        RESULT = String.valueOf(e) + "-" + String.valueOf(t);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expresion ::= termino 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 33] Termino = " + t);
        RESULT = t;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // termino ::= termino MULT factor 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 34] T * F = " + t + " * " + f);
        RESULT = String.valueOf(t) + "*" + String.valueOf(f);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // termino ::= termino DIV factor 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 35] T / F = " + t + " / " + f);
        RESULT = String.valueOf(t) + "/" + String.valueOf(f);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // termino ::= factor 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 36] Factor = " + f);
        RESULT = f;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // factor ::= ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 37] Variable valor = " + id);
        RESULT = id;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // factor ::= C_INT 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 38] Constante entera valor = " + ent);
        TS.agregar("_" + ent.toString(), "C_INT", "-", ent, 0);

        RESULT = ent;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // factor ::= C_REAL 
            {
              Object RESULT =null;
		int realleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int realright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object real = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 39] Constante real valor = " + real);
        TS.agregar("_" + real.toString(), "C_REAL", "-", real, 0);
        
        RESULT = real;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // factor ::= C_STRING 
            {
              Object RESULT =null;
		int strleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int strright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object str = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        String texto = str.toString();
        String contenido = texto.substring(1, texto.length() - 1); // quitar comillas

        System.out.println("[Regla 53] Constante string valor = " + str);
        TS.agregar("_" + contenido, "C_STRING", "-", contenido, contenido.length());
        RESULT = str;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // factor ::= HEX 
            {
              Object RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int hright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object h = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
        System.out.println("[Regla 40] Constante hexadecimal valor = " + h);
        TS.agregar("_" + h.toString(), "HEX", "-", h, 0);
        RESULT = h;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // factor ::= APARENT expresion CPARENT 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 41] Parentesis expresion parentesis = (" + e + ")");
        RESULT = "(" + e + ")";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // mostrar ::= MOSTRAR APARENT ID CPARENT 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 47] Mostrar ID = " + id);
        RESULT = String.valueOf(id);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mostrar",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // mostrar ::= MOSTRAR APARENT C_INT CPARENT 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int entright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 48] Mostrar C_INT = " + ent);
        RESULT = String.valueOf(ent);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mostrar",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // mostrar ::= MOSTRAR APARENT C_REAL CPARENT 
            {
              Object RESULT =null;
		int realleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int realright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object real = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 49] Mostrar C_REAL = " + real);
        RESULT = String.valueOf(real);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mostrar",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // mostrar ::= MOSTRAR APARENT C_STRING CPARENT 
            {
              Object RESULT =null;
		int strleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int strright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object str = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 50] Mostrar C_STRING = " + str);
        RESULT = String.valueOf(str);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mostrar",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // mostrar ::= MOSTRAR APARENT HEX CPARENT 
            {
              Object RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object h = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
        System.out.println("[Regla 51] Mostrar HEX = " + h);
        RESULT = String.valueOf(h);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mostrar",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
