
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexicoparte1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 34;
  public static final int DISTINTO = 36;
  public static final int ASIGNAR = 17;
  public static final int MULT = 24;
  public static final int INLIST = 11;
  public static final int MOSTRAR = 6;
  public static final int REPEAT = 2;
  public static final int INT = 13;
  public static final int HEX = 21;
  public static final int C_REAL = 19;
  public static final int AND = 37;
  public static final int MENORIGUAL = 31;
  public static final int IGUAL = 35;
  public static final int FP = 10;
  public static final int C_STRING = 20;
  public static final int IP = 9;
  public static final int OR = 38;
  public static final int ENDDECVAR = 8;
  public static final int CCORCHETE = 40;
  public static final int DIV = 25;
  public static final int SUMA = 22;
  public static final int IF = 3;
  public static final int ID = 16;
  public static final int MAYORIGUAL = 33;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ACORCHETE = 39;
  public static final int COMA = 29;
  public static final int MENOS = 23;
  public static final int MENOR = 30;
  public static final int REAL = 14;
  public static final int MAYOR = 32;
  public static final int DECVAR = 7;
  public static final int ELSE = 5;
  public static final int WHILE = 41;
  public static final int THEN = 4;
  public static final int END = 12;
  public static final int STRING = 15;
  public static final int C_INT = 18;
  public static final int APARENT = 26;
  public static final int CPARENT = 27;
  public static final int PYC = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "REPEAT",
  "IF",
  "THEN",
  "ELSE",
  "MOSTRAR",
  "DECVAR",
  "ENDDECVAR",
  "IP",
  "FP",
  "INLIST",
  "END",
  "INT",
  "REAL",
  "STRING",
  "ID",
  "ASIGNAR",
  "C_INT",
  "C_REAL",
  "C_STRING",
  "HEX",
  "SUMA",
  "MENOS",
  "MULT",
  "DIV",
  "APARENT",
  "CPARENT",
  "PYC",
  "COMA",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "DOSPUNTOS",
  "IGUAL",
  "DISTINTO",
  "AND",
  "OR",
  "ACORCHETE",
  "CCORCHETE",
  "WHILE"
  };
}

